twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        product_images_path: '%env(PRODUCT_IMAGES_PATH)%'

when@test:
    twig:
        strict_variables: true
